### ISSUE TITLE
Split data into train/val/test

### ISSUE THREAD

**Issue by jsadler2** [Okstate-WaDE/flood_prediction_improvement#8]
Partition | Years | Number of Years
-- | -- | -- 
Train | 2007 - 2017 | 11
Validation | 2008-2020 | 3
Test | 2021-2022 | 2

**Comment by jsadler2** [comment]
After looking at the model, it seems like the data ends before the end of 2022, so we need to revise these dates:

Partition | Years | Number of Years
-- | -- | -- 
Train | 2007 - 2016 | 10
Validation | 2017-2019 | 3
Test | 2020-2021 | 2

**Comment by ogunbajoadeyinka** [comment]
<img width="530" alt="val_tst" src="https://github.com/Okstate-WaDE/flood_prediction_improvement/assets/52512426/0644f299-74f6-4226-afc4-167393295db4">

# Defining the time periods for training, validation, and test sets
train_start, train_end = '2007-01-01', '2015-12-31'
val_start, val_end = '2016-01-01', '2018-12-31'
test_start, test_end = '2019-01-01', '2020-12-31'
